In [19]:
import pandas as pd

train_data = pd.read_csv('../CSV/HSV/HSV_Training.csv')
train_data

             H           S           V  label
0    81.974577  102.584973  168.376517      1
1    54.737978   91.916578  146.841428      1
2    76.855214   96.200118  160.534384      1
3    76.855214   96.200118  160.534384      1
4    33.478151  103.161639  147.159878      1
..         ...         ...         ...    ...
195  83.991077   82.608059  155.094844      5
196  83.991077   82.608059  155.094844      5
197  86.196517   71.111233  170.544318      5
198  86.196517   71.111233  170.544318      5
199  79.601872   92.843486  148.014420      5

[200 rows x 4 columns]

In [20]:
test_data = pd.read_csv('../CSV/HSV/HSV_Testing.csv')
test_data

            H           S           V  label
0   75.729207  143.896614  171.584803      1
1   82.076242   92.058603  188.019142      1
2   81.025352  115.197752  175.925893      1
3   83.869878  121.008110  158.315995      1
4   96.222900  112.547039  179.969918      2
5   89.591180  122.983177  182.470417      2
6   96.042360  103.192065  178.292771      2
7   85.100154  120.321136  188.340366      2
8   84.156720  100.012220  166.383919      3
9   92.305871   84.218896  148.585724      3
10  88.543263   90.975482  168.879704      3
11  85.960367   94.744448  158.527583      3
12  81.337419  126.304360  145.208996      4
13  83.778485  130.728746  141.367802      4
14  86.825147   89.269973  160.118085      4
15  86.866416   88.536443  145.672971      4
16  85.568558   83.598321  166.861402      5
17  83.429205   85.663539  152.555808      5
18  80.345980   87.106492  165.890041      5
19  84.719641   71.449225  179.965003      5

In [21]:
X_train = train_data.drop('label', axis=1)
y_train = train_data['label']

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.decomposition import PCA

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=3)),
    ('classifier', GaussianNB()) 
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=3)),
                ('classifier', GaussianNB())])

In [23]:
X_test = test_data.drop('label', axis=1)
y_true = test_data['label']

In [24]:
y_pred = pipeline.predict(X_test)
y_pred

array([1, 1, 1, 4, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 3, 5, 3, 5, 5, 1],
      dtype=int64)

In [25]:
X_test['label'] = y_pred
X_test

            H           S           V  label
0   75.729207  143.896614  171.584803      1
1   82.076242   92.058603  188.019142      1
2   81.025352  115.197752  175.925893      1
3   83.869878  121.008110  158.315995      4
4   96.222900  112.547039  179.969918      2
5   89.591180  122.983177  182.470417      2
6   96.042360  103.192065  178.292771      2
7   85.100154  120.321136  188.340366      2
8   84.156720  100.012220  166.383919      3
9   92.305871   84.218896  148.585724      3
10  88.543263   90.975482  168.879704      3
11  85.960367   94.744448  158.527583      3
12  81.337419  126.304360  145.208996      4
13  83.778485  130.728746  141.367802      4
14  86.825147   89.269973  160.118085      3
15  86.866416   88.536443  145.672971      5
16  85.568558   83.598321  166.861402      3
17  83.429205   85.663539  152.555808      5
18  80.345980   87.106492  165.890041      5
19  84.719641   71.449225  179.965003      1

In [26]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_true, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.75

In [27]:
# import joblib

# # simpan model dalam file .pkl
# joblib.dump(pipeline, '../Model/NaiveBayes4.pkl')